import Head from "next/head";
// Library
import Prismic from "@prismicio/client";
import convertPrismicToData from "../utils/convertPrismicToData";
// Components
import Header from "../components/Header";
import BlogPostArchiveLink from "../components/BlogPostArchiveLink";
// Styles
import styles from "../styles/ArchivesPage.module.css";

// One day in seconds
const ONE_DAY_IN_SECONDS = 86400;

// Function Connect to Prismic
export async function getStaticProps(context) {
  // Connect to prismic
  const apiEndpoint = "https://cakurang-try-prismic.prismic.io/api/v2";
  const client = Prismic.client(apiEndpoint);
  // Query from Prismic
  const data = await client.query(
    Prismic.Predicates.at("document.type", "blog_post"),
    { orderings: "[my.blog_post.publish_date desc]" }
  );

  const posts = data.results.map(convertPrismicToData);

  return {
    props: {
      posts,
      revalidate: ONE_DAY_IN_SECONDS, // one day,
    },
  };
}

export default function Archives({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Archives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <h1 className={styles.title}>Archives</h1>
        {posts.map((p) => {
          return (
            <div key={p.slug} className={styles.post}>
              <BlogPostArchiveLink {...p} />
            </div>
          );
        })}
      </main>
    </div>
  );
}
